CREATE DATABASE PartitioningTest
 

--creating filegroups
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2014]
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2015]
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2016]
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2017]
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2018]
ALTER DATABASE [PartitioningTest] ADD FILEGROUP [LOG_2019]



--creating files
ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2014', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2014.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2014]

ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2015', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2015.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2015]

ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2016', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2016.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2016]

ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2017', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2017.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2017]

ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2018', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2018.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2018]

ALTER DATABASE [PartitioningTest] ADD FILE ( NAME = N'LOG_2019', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PartitioningTest_LOG2019.ndf' , SIZE = 10MB , FILEGROWTH = 10MB ) TO FILEGROUP [LOG_2019]