  ALTER PARTITION FUNCTION YearlyPartitionWithCurentYearQuarterly ()  
MERGE RANGE ('2019-03-01')
 ALTER PARTITION FUNCTION YearlyPartitionWithCurentYearQuarterly ()  
MERGE RANGE ('2019-06-01')
 ALTER PARTITION FUNCTION YearlyPartitionWithCurentYearQuarterly ()  
MERGE RANGE ('2020-09-01')
